export const styles = {
  // Global Container
  container: {
    minHeight: '100vh',
    backgroundColor: '#f8fafc',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  },

  // ----- Header Base Styles -----
  header: {
    backgroundColor: '#7C2A62',
    color: 'white',
    boxShadow: '0 4px 20px rgba(124, 42, 98, 0.3)',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },

  headerTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.8rem 1rem',
    borderBottom: '1px solid rgba(255,255,255,0.1)',
    flexWrap: 'wrap',
  },

  headerBottom: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.5rem 1rem',
    backgroundColor: 'rgba(255,255,255,0.05)',
    overflowX: 'auto',
  },

  // Logo Section
  logoSection: {
    display: 'flex',
    alignItems: 'center',
  },
  logoContainer: {
    display: 'flex',
    flexDirection: 'column',
  },
  logo: {
    fontSize: '1.4rem',
    margin: 0,
    fontWeight: 'bold',
    background: 'linear-gradient(135deg, #fff, #F7D9EB)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  logoSubtitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginTop: '0.25rem',
  },
  subtitleText: {
    fontSize: '0.85rem',
    opacity: 0.9,
    fontWeight: '500',
  },

  // User Section
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    flexShrink: 0,
  },
  userWelcome: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  welcomeText: {
    fontSize: '0.8rem',
    opacity: 0.8,
  },
  userName: {
    fontSize: '0.85rem',
    fontWeight: '500',
  },
  userAvatarContainer: {
    position: 'relative',
    cursor: 'pointer',
  },
  userAvatar: {
    width: '34px',
    height: '34px',
    fontSize: '1rem',
    borderRadius: '50%',
    backgroundColor: '#F7D9EB',
    color: '#7C2A62',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    border: '2px solid rgba(255, 255, 255, 0.3)',
    transition: 'all 0.3s ease',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },

  // Navigation Styles
  navSection: {
    display: 'flex',
    alignItems: 'center',
  },
  nav: {
    display: 'flex',
    gap: '0.3rem',
    flexWrap: 'nowrap',
  },
  navButton: {
    padding: '0.45rem 0.75rem',
    fontSize: '0.78rem',
    borderRadius: '6px',
    whiteSpace: 'nowrap',
    border: 'none',
    backgroundColor: 'transparent',
    color: 'rgba(255, 255, 255, 0.8)',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  activeNavButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    color: 'white',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
  },
  navIcon: {
    fontSize: '1.1rem',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },

  // Profile Dropdown Styles
  profileDropdown: {
    position: 'absolute',
    top: '100%',
    right: 0,
    width: '300px',
    backgroundColor: 'white',
    borderRadius: '12px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    zIndex: 2000,
    marginTop: '0.5rem',
    overflow: 'hidden',
  },
  profileDropdownHeader: {
    padding: '1rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
  },
  profileDropdownTitle: {
    margin: 0,
    fontSize: '1.1rem',
    fontWeight: '600',
  },
  profileDropdownContent: {
    padding: '1rem 1.5rem',
    borderBottom: '1px solid #f0f0f0',
  },
  profileDetailItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.5rem 0',
    borderBottom: '1px solid #f8f8f8',
  },
  profileDetailLabel: {
    color: '#666',
    fontSize: '0.9rem',
    fontWeight: '500',
  },
  profileDetailValue: {
    color: '#333',
    fontSize: '0.9rem',
    fontWeight: '600',
  },
  profileDropdownActions: {
    padding: '1rem 1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  viewProfileButton: {
    width: '100%',
    padding: '0.75rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  uploadPhotoButton: {
    width: '100%',
    padding: '0.75rem',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },

  // Profile Photo Styles
  profilePhotoModal: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    maxWidth: '500px',
    width: '90%',
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  profilePhotoHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    borderBottom: '2px solid #F7D9EB',
    paddingBottom: '1rem',
  },
  profilePhotoPreviewSection: {
    border: '2px dashed #F7D9EB',
    borderRadius: '10px',
    padding: '2rem',
    textAlign: 'center',
    marginBottom: '1.5rem',
    minHeight: '200px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilePhotoImageContainer: {
    width: '100%',
    maxHeight: '300px',
    overflow: 'hidden',
    borderRadius: '8px',
  },
  profilePhotoImage: {
    width: '100%',
    height: 'auto',
    maxHeight: '300px',
    objectFit: 'contain',
  },
  profilePhotoRequirements: {
    backgroundColor: '#f8f5ff',
    padding: '1rem',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    border: '1px solid #F7D9EB',
  },
  removePhotoButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#FF6B6B',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  profilePhotoSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    marginBottom: '2rem',
    textAlign: 'center',
  },
  profilePhotoContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1rem',
  },
  profilePhotoPreview: {
    width: '120px',
    height: '120px',
    borderRadius: '50%',
    backgroundColor: '#F7D9EB',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    border: '4px solid #7C2A62',
  },
  profilePhotoPlaceholder: {
    fontSize: '3rem',
    color: '#7C2A62',
    fontWeight: 'bold',
  },
  profilePhotoActions: {
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },

  // Phone Input Styles
  phoneInputContainer: {
    display: 'flex',
    alignItems: 'center',
    border: '2px solid #F7D9EB',
    borderRadius: '8px',
    overflow: 'hidden',
    backgroundColor: 'white',
    transition: 'border-color 0.3s ease',
  },
  phonePrefix: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.75rem',
    backgroundColor: '#f8f5ff',
    borderRight: '1px solid #F7D9EB',
    fontWeight: '600',
    color: '#7C2A62',
    fontSize: '0.9rem',
  },
  indianFlag: {
    fontSize: '1.1rem',
  },
  countryCode: {
    fontSize: '0.9rem',
  },
  phoneInput: {
    flex: 1,
    padding: '0.75rem',
    border: 'none',
    outline: 'none',
    fontSize: '1rem',
    backgroundColor: 'transparent',
    fontFamily: 'inherit',
  },
  phoneValidationMessage: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginTop: '0.25rem',
    fontSize: '0.8rem',
    color: '#4CAF50',
  },
  validPhoneIcon: {
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  validPhoneText: {
    color: '#4CAF50',
    fontSize: '0.8rem',
  },

  // Form Styles
  formActions: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'flex-end',
    marginTop: '2rem',
    paddingTop: '1.5rem',
    borderTop: '2px solid #F7D9EB',
  },
  updateButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    transition: 'all 0.3s ease',
  },
  updateButtonDisabled: {
    backgroundColor: '#cccccc',
    cursor: 'not-allowed',
  },
  nonEditableField: {
    backgroundColor: '#f5f5f5',
    color: '#666',
    cursor: 'not-allowed',
    borderColor: '#ddd',
  },
  fieldNote: {
    color: '#666',
    fontSize: '0.8rem',
    marginTop: '0.25rem',
    fontStyle: 'italic',
  },

  // Address Form Styles
  addressForm: {
    marginBottom: '20px',
    padding: '16px',
    backgroundColor: '#f8f9fa',
    borderRadius: '8px',
    border: '1px solid #e9ecef',
  },
  addressFormTitle: {
    margin: '0 0 16px 0',
    fontSize: '16px',
    fontWeight: '600',
    color: '#333',
  },
  addressFormGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  addressInput: {
    padding: '12px',
    border: '1px solid #ddd',
    borderRadius: '6px',
    fontSize: '14px',
    outline: 'none',
    transition: 'border-color 0.3s ease',
    gridColumn: 'span 1',
  },
  addressInputFull: {
    gridColumn: 'span 2',
  },

  // Back to Cart Button
  backToCartButton: {
    width: '100%',
    padding: '12px',
    backgroundColor: 'transparent',
    color: '#6c757d',
    border: '1px solid #6c757d',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: '500',
    marginTop: '12px',
    transition: 'all 0.3s ease',
  },
  backToCartButtonHover: {
    backgroundColor: '#6c757d',
    color: 'white',
  },

  // Icons and Badges
  cartIconContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.5rem',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    border: '1px solid rgba(255, 255, 255, 0.2)',
  },
  cartIcon: {
    position: 'relative',
    fontSize: '1.5rem',
  },
  cartBadge: {
    position: 'absolute',
    top: '-8px',
    right: '-8px',
    backgroundColor: '#FF6B6B',
    color: 'white',
    borderRadius: '50%',
    width: '20px',
    height: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.75rem',
    fontWeight: 'bold',
    border: '2px solid #7C2A62',
  },
  goldenStars: {
    color: '#FFD700',
    fontSize: '1.1rem',
  },
  uploadIcon: {
    marginRight: '0.5rem',
    fontSize: '1rem',
  },

  // Notification Styles
  notificationContainer: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    padding: '0.5rem',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    border: '1px solid rgba(255, 255, 255, 0.2)',
  },
  notificationBell: {
    position: 'relative',
    fontSize: '1.5rem',
  },
  notificationBadge: {
    position: 'absolute',
    top: '-8px',
    right: '-8px',
    backgroundColor: '#FF6B6B',
    color: 'white',
    borderRadius: '50%',
    width: '20px',
    height: '20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.75rem',
    fontWeight: 'bold',
    border: '2px solid #7C2A62',
  },
  notificationDropdown: {
  position: 'absolute',
  top: '100%',
  right: 0,
  width: '400px',
  backgroundColor: 'white',
  borderRadius: '12px',
  boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
  zIndex: 2000,
  maxHeight: '500px',
  overflow: 'hidden', // Changed from 'auto' to 'hidden'
  display: 'flex',
  flexDirection: 'column',
},
  notificationHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 1.5rem',
    borderBottom: '1px solid #f0f0f0',
    backgroundColor: '#f8f9fa',
  },
  notificationTitle: {
    margin: 0,
    color: '#7C2A62',
    fontSize: '1.1rem',
  },
  markAllReadButton: {
    background: 'none',
    border: 'none',
    color: '#7C2A62',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: '500',
  },
 notificationList: {
  maxHeight: '400px',
  overflowY: 'auto',
  // Hide scrollbar for different browsers
  scrollbarWidth: 'none', // Firefox
  '&::-webkit-scrollbar': {
    display: 'none', // Chrome, Safari, Edge
  },
  msOverflowStyle: 'none', // IE and Edge
},

// Alternative approach if you want to keep some scroll functionality but make it invisible:
notificationListAlt: {
  maxHeight: '400px',
  overflowY: 'auto',
  paddingRight: '0px', // Ensure no extra space for scrollbar
  '&::-webkit-scrollbar': {
    width: '0px',
    background: 'transparent',
  },
  '&::-webkit-scrollbar-thumb': {
    background: 'transparent',
  },
},
  notificationItem: {
    display: 'flex',
    padding: '1rem 1.5rem',
    borderBottom: '1px solid #f0f0f0',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
  },
  unreadNotification: {
    backgroundColor: '#f8f5ff',
  },
  readNotification: {
    backgroundColor: 'white',
  },
  notificationIcon: {
    fontSize: '1.2rem',
    marginRight: '1rem',
    width: '24px',
    textAlign: 'center',
  },
  notificationContent: {
    flex: 1,
  },
  notificationItemTitle: {
    margin: '0 0 0.25rem 0',
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#333',
  },
  notificationMessage: {
    margin: '0 0 0.5rem 0',
    fontSize: '0.85rem',
    color: '#666',
    lineHeight: '1.4',
  },
  notificationTime: {
    fontSize: '0.75rem',
    color: '#999',
  },
  noNotifications: {
    textAlign: 'center',
    padding: '2rem',
    color: '#666',
    margin: 0,
  },

  // Logout Styles
  logoutButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: 'white',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.95rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s ease',
  },
  logoutIcon: {
    fontSize: '1.1rem',
  },
  

  // Main Content Styles
  mainContent: {
    marginTop: '110px',
    padding: '1rem',
  },
  welcomeSection: {
    padding: '2rem',
    textAlign: 'center',
    backgroundColor: 'white',
    borderRadius: '15px',
    marginBottom: '2rem',
  },
  welcomeTitle: {
    fontSize: '2.5rem',
    marginBottom: '1rem',
    color: '#7C2A62',
  },
  welcomeSubtitle: {
    fontSize: '1.2rem',
    color: '#666',
  },

  // Services Section
  servicesSection: {
    padding: '2rem',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  serviceGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '2rem',
  },
  serviceCard: {
    padding: '2rem',
    backgroundColor: 'white',
    borderRadius: '15px',
    boxShadow: '0 5px 20px rgba(124, 42, 98, 0.1)',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    border: '2px solid transparent',
  },
  serviceIcon: {
    fontSize: '3rem',
    marginBottom: '1rem',
  },
  serviceTitle: {
    fontSize: '1.5rem',
    marginBottom: '1rem',
    color: '#7C2A62',
  },
  serviceDescription: {
    color: '#666',
    marginBottom: '1.5rem',
    lineHeight: '1.5',
  },
  serviceButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    fontWeight: '600',
    transition: 'all 0.3s ease',
  },

  // Medicine Page Styles
  medicineLayout: {
    padding: '2rem',
    maxWidth: '1200px',
    margin: '140px auto 0',
    minHeight: 'calc(100vh - 140px)',
  },
  fullWidthContent: {
    width: '100%',
  },
  searchSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    marginBottom: '1.5rem',
  },
  searchContainer: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  searchInput: {
    flex: 1,
    padding: '1rem',
    border: '2px solid #F7D9EB',
    borderRadius: '10px',
    fontSize: '1rem',
    transition: 'border-color 0.3s ease',
  },
  searchButton: {
    padding: '1rem 2rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: '600',
  },

  // Prescription Upload Styles
  prescriptionUploadLabel: {
    padding: '1rem 1.5rem',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s ease',
    whiteSpace: 'nowrap',
  },

  // Products Section
  productsSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    marginBottom: '1.5rem',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  sectionTitle: {
    color: '#7C2A62',
    fontSize: '1.5rem',
    margin: 0,
  },
  resultsCount: {
    color: '#666',
    fontSize: '0.9rem',
  },
  sectionSubtitle: {
    color: '#666',
    fontSize: '0.9rem',
    margin: 0,
  },
  productsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '1.5rem',
  },
  productCard: {
    border: '2px solid #F7D9EB',
    borderRadius: '12px',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    transition: 'all 0.3s ease',
    backgroundColor: 'white',
  },
  productInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  productName: {
    margin: '0 0 0.5rem 0',
    color: '#7C2A62',
    fontSize: '1.1rem',
    fontWeight: '600',
  },
  productVendor: {
    margin: '0 0 0.5rem 0',
    color: '#666',
    fontSize: '0.9rem',
  },
  productCategory: {
    marginBottom: '1rem',
  },
  categoryBadge: {
    padding: '0.25rem 0.75rem',
    backgroundColor: '#F7D9EB',
    color: '#7C2A62',
    borderRadius: '12px',
    fontSize: '0.8rem',
    fontWeight: '500',
  },
  productFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
  },
  productPrice: {
    color: '#7C2A62',
    fontWeight: 'bold',
    fontSize: '1.2rem',
    margin: 0,
  },
  addToCartButton: {
    padding: '0.75rem 1rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    transition: 'all 0.3s ease',
  },

  // Quantity Controls
  quantityControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  quantityButton: {
    width: '32px',
    height: '32px',
    border: '1px solid #7C2A62',
    backgroundColor: 'transparent',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '&:disabled': {
      opacity: 0.5,
      cursor: 'not-allowed',
    },
  },
  quantity: {
    padding: '0 0.5rem',
    fontWeight: '600',
    minWidth: '30px',
    textAlign: 'center',
  },

  // Pharmacies Section
  pharmaciesSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  pharmaciesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '1.5rem'
  },
  pharmacyCard: {
    border: '2px solid #F7D9EB',
    borderRadius: '12px',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    transition: 'all 0.3s ease',
    cursor: 'pointer'
  },
  pharmacyHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem'
  },
  pharmacyIcon: {
    fontSize: '2rem',
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7D9EB',
    borderRadius: '10px'
  },
  pharmacyInfo: {
    flex: 1
  },
  pharmacyName: {
    margin: '0 0 0.25rem 0',
    color: '#7C2A62',
    fontSize: '1.1rem',
    fontWeight: '600'
  },
  pharmacyRating: {
    color: '#FFD700',
    fontWeight: 'bold',
    fontSize: '0.9rem'
  },
  pharmacyDetails: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem'
  },
  pharmacyDetailItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center'
  },
  pharmacyDetailLabel: {
    color: '#666',
    fontSize: '0.9rem',
    fontWeight: '500'
  },
  pharmacyDetailValue: {
    color: '#333',
    fontSize: '0.9rem',
    fontWeight: '600'
  },
  feeValue: {
    color: '#7C2A62',
    fontWeight: 'bold',
    fontSize: '1rem',
  },
  viewButton: {
    padding: '0.75rem 1rem',
    border: '1px solid #7C2A62',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    transition: 'all 0.3s ease',
    marginTop: '0.5rem'
  },

  // Enhanced View Store Button Styles
  viewStoreButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.95rem',
    transition: 'all 0.3s ease',
    marginTop: '1rem',
    width: '100%',
    textTransform: 'none',
    letterSpacing: '0.5px',
    position: 'relative',
    overflow: 'hidden',
    '&:hover': {
      backgroundColor: '#7C2A62',
      color: 'white',
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 15px rgba(124, 42, 98, 0.4)'
    },
    '&:active': {
      transform: 'translateY(0)',
      boxShadow: '0 2px 5px rgba(124, 42, 98, 0.3)'
    },
    '&:focus': {
      outline: 'none',
      boxShadow: '0 0 0 3px rgba(124, 42, 98, 0.3)'
    },
    '&:disabled': {
      backgroundColor: '#cccccc',
      borderColor: '#cccccc',
      color: '#666666',
      cursor: 'not-allowed',
      transform: 'none',
      boxShadow: 'none',
      '&:hover': {
        backgroundColor: '#cccccc',
        color: '#666666',
        transform: 'none',
        boxShadow: 'none'
      }
    }
  },

  // Alternative filled style
  viewStoreButtonFilled: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: '2px solid #7C2A62',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.95rem',
    transition: 'all 0.3s ease',
    marginTop: '1rem',
    width: '100%',
    textTransform: 'none',
    letterSpacing: '0.5px',
    boxShadow: '0 2px 8px rgba(124, 42, 98, 0.3)',
    '&:hover': {
      backgroundColor: '#6a2355',
      borderColor: '#6a2355',
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 15px rgba(124, 42, 98, 0.4)'
    },
    '&:active': {
      transform: 'translateY(0)',
      boxShadow: '0 2px 5px rgba(124, 42, 98, 0.3)'
    }
  },

  // Gradient style with hover
  viewStoreButtonGradient: {
    padding: '0.75rem 1.5rem',
    background: 'linear-gradient(135deg, transparent 0%, transparent 100%)',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.95rem',
    transition: 'all 0.3s ease',
    marginTop: '1rem',
    width: '100%',
    textTransform: 'none',
    letterSpacing: '0.5px',
    position: 'relative',
    overflow: 'hidden',
    '&:hover': {
      background: 'linear-gradient(135deg, #7C2A62 0%, #9c4d81 100%)',
      color: 'white',
      borderColor: '#7C2A62',
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 15px rgba(124, 42, 98, 0.4)'
    }
  },

  // Small version
  viewStoreButtonSmall: {
    padding: '0.5rem 1rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.85rem',
    transition: 'all 0.2s ease',
    marginTop: '0.5rem',
    width: 'auto',
    minWidth: '120px',
    '&:hover': {
      backgroundColor: '#7C2A62',
      color: 'white',
      transform: 'translateY(-1px)',
      boxShadow: '0 3px 10px rgba(124, 42, 98, 0.3)'
    }
  },

  // With icon
  viewStoreButtonWithIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.75rem 1.5rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '10px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.95rem',
    transition: 'all 0.3s ease',
    marginTop: '1rem',
    width: '100%',
    '&:hover': {
      backgroundColor: '#7C2A62',
      color: 'white',
      transform: 'translateY(-2px)',
      boxShadow: '0 4px 15px rgba(124, 42, 98, 0.4)'
    }
  },

  // Pharmacy Search
  pharmacySearchContainer: {
    margin: '0.5rem 0',
  },
  pharmacySearchInputSmall: {
    width: '100%',
    padding: '0.75rem',
    border: '1px solid #F7D9EB',
    borderRadius: '8px',
    fontSize: '0.9rem',
  },
  pharmacySearchSection: {
    marginBottom: '1.5rem',
  },
  pharmacySearchInput: {
    width: '100%',
    padding: '1rem',
    border: '2px solid #F7D9EB',
    borderRadius: '10px',
    fontSize: '1rem',
  },

  // Cart Page Styles
  cartPageContainer: {
    marginTop: '140px',
    padding: '2rem',
    maxWidth: '1200px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  cartPageContent: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '2rem',
    alignItems: 'start',
  },
  cartItemsSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  cartSummarySection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    position: 'sticky',
    top: '160px',
  },
  summaryCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  summaryTitle: {
    color: '#7C2A62',
    fontSize: '1.3rem',
    margin: 0,
  },
  summaryDetails: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '0.5rem',
    borderBottom: '1px solid #f0f0f0',
  },
  grandTotal: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: '1rem',
    borderTop: '2px solid #7C2A62',
    fontWeight: 'bold',
    fontSize: '1.1rem',
    color: '#7C2A62',
  },
  freeDelivery: {
    color: '#28a745',
    fontWeight: '600',
  },

  // Cart Items
  cartHeader: {
    borderBottom: '2px solid #F7D9EB',
    paddingBottom: '1rem',
    marginBottom: '1rem',
  },
  cartTitle: {
    margin: '0 0 0.25rem 0',
    color: '#7C2A62',
    fontSize: '1.3rem',
  },
  cartSubtitle: {
    margin: 0,
    color: '#666',
    fontSize: '0.9rem',
  },
  cartItems: {
    marginBottom: '2rem',
  },
  cartItemsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  emptyCart: {
    textAlign: 'center',
    padding: '3rem 1rem',
    color: '#666',
  },
  emptyCartIcon: {
    fontSize: '4rem',
    marginBottom: '1rem',
  },
  emptyCartText: {
    margin: '0 0 0.5rem 0',
    fontSize: '1.3rem',
    fontWeight: '600',
  },
  emptyCartSubtext: {
    margin: '0 0 2rem 0',
    fontSize: '1rem',
  },
  cartItem: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr auto',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem',
    border: '1px solid #F7D9EB',
    borderRadius: '8px',
    backgroundColor: '#fafafa',
  },
  cartItemInfo: {
    display: 'flex',
    flexDirection: 'column',
  },
  cartItemName: {
    margin: '0 0 0.25rem 0',
    fontSize: '1rem',
    color: '#7C2A62',
    fontWeight: '600',
  },
  cartItemVendor: {
    margin: '0 0 0.25rem 0',
    fontSize: '0.8rem',
    color: '#666',
  },
  cartItemPrice: {
    margin: 0,
    fontSize: '0.9rem',
    color: '#7C2A62',
  },
  itemTotal: {
    fontWeight: 'bold',
    color: '#7C2A62',
    fontSize: '1rem',
    textAlign: 'center',
  },
  removeButton: {
    width: '32px',
    height: '32px',
    border: 'none',
    backgroundColor: '#ff4444',
    color: 'white',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '1.2rem',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkoutButtonLarge: {
    width: '100%',
    padding: '1rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '1rem',
    transition: 'all 0.3s ease',
  },
  shopNowButton: {
    padding: '1rem 2rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: '600',
  },

  // Orders Page
  ordersContainer: {
    marginTop: '140px',
    padding: '2rem',
    maxWidth: '1200px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  ordersList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  orderCard: {
    backgroundColor: 'white',
    borderRadius: '15px',
    padding: '2rem',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  orderHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '1.5rem',
  },
  orderId: {
    margin: '0 0 0.5rem 0',
    color: '#7C2A62',
    fontSize: '1.2rem',
  },
  orderDate: {
    margin: '0 0 0.25rem 0',
    color: '#666',
    fontSize: '0.9rem',
  },
  paymentId: {
    margin: 0,
    color: '#666',
    fontSize: '0.8rem',
    fontFamily: 'monospace',
  },
  orderStatus: {
    textAlign: 'right',
  },
  statusBadge: {
    padding: '0.5rem 1rem',
    borderRadius: '20px',
    color: 'white',
    fontSize: '0.8rem',
    fontWeight: '600',
  },
  orderItems: {
    marginBottom: '1.5rem',
  },
  orderItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.75rem 0',
    borderBottom: '1px solid #F7D9EB',
  },
  itemName: {
    flex: 2,
    color: '#333',
  },
  itemQuantity: {
    flex: 1,
    color: '#666',
    textAlign: 'center',
  },
  itemPrice: {
    flex: 1,
    color: '#7C2A62',
    fontWeight: '600',
    textAlign: 'right',
  },
  orderFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: '1rem',
    borderTop: '2px solid #F7D9EB',
  },
  orderAddress: {
    color: '#666',
    fontSize: '0.9rem',
  },
  orderTotal: {
    color: '#7C2A62',
    fontSize: '1.1rem',
    fontWeight: 'bold',
  },
  orderActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  trackButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: '600',
  },
  noOrders: {
    textAlign: 'center',
    padding: '3rem',
    backgroundColor: 'white',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  noOrdersText: {
    fontSize: '1.2rem',
    color: '#666',
    marginBottom: '1.5rem',
  },

  // Profile Page
  profileContainer: {
    marginTop: '140px',
    padding: '2rem',
    maxWidth: '800px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  profileHeader: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginBottom: '2rem',
  },
  editProfileButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: '600',
  },
  profileForm: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '1.5rem',
    marginBottom: '2rem',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
  },
  formLabel: {
    marginBottom: '0.5rem',
    color: '#7C2A62',
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  formInput: {
    padding: '0.75rem',
    border: '2px solid #F7D9EB',
    borderRadius: '8px',
    fontSize: '1rem',
    transition: 'border-color 0.3s ease',
    cursor: 'text',
  },
  formInputError: {
    borderColor: '#FF6B6B !important',
  },
  formError: {
    color: '#FF6B6B',
    fontSize: '0.8rem',
    marginTop: '0.25rem',
  },
  formTextarea: {
    padding: '0.75rem',
    border: '2px solid #F7D9EB',
    borderRadius: '8px',
    fontSize: '1rem',
    resize: 'vertical',
    minHeight: '80px',
    fontFamily: 'inherit',
    cursor: 'text',
  },
  formNote: {
    marginBottom: '1.5rem',
    padding: '1rem',
    backgroundColor: '#f8f5ff',
    borderRadius: '8px',
    border: '1px solid #F7D9EB',
  },
  noteText: {
    margin: 0,
    color: '#666',
    fontSize: '0.9rem',
  },

  // Consultation Page
  consultationContainer: {
    marginTop: '140px',
    padding: '2rem',
    maxWidth: '1400px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  consultationHeader: {
    textAlign: 'center',
    marginBottom: '2rem',
  },
  consultationSubtitle: {
    fontSize: '1.1rem',
    color: '#666',
    marginTop: '0.5rem',
  },
  consultationLayout: {
    display: 'grid',
    gridTemplateColumns: '1fr 3fr',
    gap: '2rem',
    alignItems: 'start',
  },
  filterPanel: {
    backgroundColor: 'white',
    padding: '1.5rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    height: 'fit-content',
    position: 'sticky',
    top: '160px',
  },
  filterTitle: {
    color: '#7C2A62',
    marginBottom: '1.5rem',
    fontSize: '1.2rem',
    fontWeight: '600',
  },
  filterGroup: {
    marginBottom: '1.5rem',
  },
  filterLabel: {
    display: 'block',
    marginBottom: '0.5rem',
    color: '#7C2A62',
    fontWeight: '500',
    fontSize: '0.9rem',
  },
  filterSelect: {
    width: '100%',
    padding: '0.75rem',
    border: '2px solid #F7D9EB',
    borderRadius: '8px',
    backgroundColor: 'white',
    fontSize: '0.9rem',
  },
  clearFiltersButton: {
    width: '100%',
    padding: '0.75rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    marginTop: '1rem',
  },
  doctorsList: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  doctorsTitle: {
    color: '#7C2A62',
    marginBottom: '1.5rem',
    fontSize: '1.3rem',
  },
  noDoctors: {
    textAlign: 'center',
    padding: '3rem',
    color: '#666',
  },
  doctorsGrid: {
    display: 'grid',
    gap: '1.5rem',
  },
  doctorCard: {
    border: '2px solid #F7D9EB',
    borderRadius: '12px',
    padding: '1.5rem',
    transition: 'all 0.3s ease',
  },
  doctorHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '1rem',
  },
  doctorImage: {
    fontSize: '3rem',
  },
  doctorBasicInfo: {
    flex: 1,
  },
  doctorName: {
    margin: '0 0 0.5rem 0',
    color: '#7C2A62',
    fontSize: '1.2rem',
  },
  doctorSpecialty: {
    margin: '0 0 0.5rem 0',
    color: '#666',
    fontSize: '0.9rem',
  },
  doctorRating: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  ratingText: {
    color: '#666',
    fontSize: '0.9rem',
  },
  doctorDetails: {
    marginBottom: '1rem',
  },
  doctorDetailItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.5rem 0',
    borderBottom: '1px solid #f0f0f0',
  },
  doctorDetailLabel: {
    color: '#666',
    fontSize: '0.9rem',
  },
  doctorDetailValue: {
    color: '#333',
    fontSize: '0.9rem',
  },
  doctorActions: {
    display: 'flex',
    gap: '1rem',
  },
  bookButton: {
    flex: 2,
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  messageButton: {
    flex: 1,
    padding: '0.75rem 1rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },

  // Filter Tabs
  filterTabs: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '2rem',
    flexWrap: 'wrap',
  },
  filterTab: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'white',
    color: '#7C2A62',
    border: '2px solid #F7D9EB',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    transition: 'all 0.3s ease',
  },
  activeFilterTab: {
    backgroundColor: '#7C2A62',
    color: 'white',
    borderColor: '#7C2A62',
  },

  // Appointments
  appointmentsContainer: {
    marginTop: '140px',
    padding: '2rem',
    maxWidth: '1200px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  appointmentsHeader: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginBottom: '2rem',
  },
  newAppointmentButton: {
    padding: '1rem 2rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: '600',
  },
  appointmentsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  appointmentCard: {
    backgroundColor: 'white',
    borderRadius: '15px',
    padding: '2rem',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  appointmentHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '1.5rem',
  },
  appointmentId: {
    margin: '0 0 0.5rem 0',
    color: '#7C2A62',
    fontSize: '1.2rem',
  },
  appointmentDoctor: {
    margin: '0 0 0.25rem 0',
    color: '#333',
    fontSize: '1.1rem',
    fontWeight: '600',
  },
  appointmentSpecialty: {
    margin: 0,
    color: '#666',
    fontSize: '0.9rem',
  },
  appointmentDetails: {
    marginBottom: '1.5rem',
  },
  detailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.5rem 0',
    borderBottom: '1px solid #f0f0f0',
  },
  appointmentActions: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'flex-end',
  },
  rescheduleButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#FF9800',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  cancelAppointmentButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#FF6B6B',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  viewDetailsButton: {
    padding: '0.5rem 1rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '1px solid #7C2A62',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  noAppointments: {
    textAlign: 'center',
    padding: '3rem',
    backgroundColor: 'white',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  noAppointmentsText: {
    fontSize: '1.2rem',
    color: '#666',
    marginBottom: '1.5rem',
  },
  bookAppointmentButton: {
    padding: '1rem 2rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: '600',
  },

  // Modal Styles
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 2000,
  },
  confirmationModal: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    maxWidth: '500px',
    width: '90%',
  },
  confirmationTitle: {
    color: '#7C2A62',
    marginBottom: '1rem',
    fontSize: '1.5rem',
    textAlign: 'center',
  },
  confirmationText: {
    color: '#666',
    marginBottom: '1.5rem',
    textAlign: 'center',
    lineHeight: '1.5',
  },
  confirmationItems: {
    marginBottom: '1.5rem',
    maxHeight: '200px',
    overflowY: 'auto',
  },
  confirmationItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.5rem 0',
    borderBottom: '1px solid #f0f0f0',
  },
  confirmationActions: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'center',
  },
  cancelButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  confirmButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },

  // Prescription Modal
  prescriptionModal: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    maxWidth: '600px',
    width: '90%',
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  prescriptionPreview: {
    border: '2px dashed #F7D9EB',
    borderRadius: '10px',
    padding: '2rem',
    textAlign: 'center',
    marginBottom: '1.5rem',
    minHeight: '200px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  prescriptionImageContainer: {
    position: 'relative',
    width: '100%',
    maxHeight: '300px',
    overflow: 'hidden',
    borderRadius: '8px',
  },
  prescriptionImage: {
    width: '100%',
    height: 'auto',
    maxHeight: '300px',
    objectFit: 'contain',
  },
  fileInfoOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    color: 'white',
    padding: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  fileInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    justifyContent: 'center',
  },
  fileIcon: {
    fontSize: '2rem',
  },
  fileName: {
    margin: '0 0 0.25rem 0',
    fontWeight: '600',
    color: '#333',
  },
  fileSize: {
    margin: 0,
    color: '#666',
    fontSize: '0.9rem',
  },
  uploadPrompt: {
    textAlign: 'center',
  },
  uploadIconLarge: {
    fontSize: '3rem',
    marginBottom: '1rem',
    color: '#7C2A62',
  },
  uploadText: {
    margin: '0 0 0.5rem 0',
    color: '#666',
    fontSize: '1.1rem',
  },
  uploadSubtext: {
    margin: 0,
    color: '#999',
    fontSize: '0.9rem',
  },
  prescriptionRequirements: {
    backgroundColor: '#f8f5ff',
    padding: '1rem',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    border: '1px solid #F7D9EB',
  },
  requirementsTitle: {
    color: '#7C2A62',
    margin: '0 0 0.5rem 0',
    fontSize: '1rem',
  },
  requirementsList: {
    margin: 0,
    paddingLeft: '1.5rem',
    color: '#666',
    fontSize: '0.9rem',
    lineHeight: '1.5',
  },
  modalActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  uploadButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  submitButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },

  // Logout Confirmation Modal
  logoutConfirmationModal: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    maxWidth: '400px',
    width: '90%',
    textAlign: 'center',
  },
  logoutConfirmationIcon: {
    fontSize: '4rem',
    marginBottom: '1rem',
  },
  logoutConfirmationTitle: {
    color: '#7C2A62',
    marginBottom: '1rem',
    fontSize: '1.5rem',
  },
  logoutConfirmationText: {
    color: '#666',
    marginBottom: '2rem',
    lineHeight: '1.5',
  },
  logoutConfirmationActions: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'center',
  },
  logoutCancelButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    flex: 1,
  },
  logoutConfirmButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    flex: 1,
  },

  // Pharmacy Store Modal
  pharmacyStoreModal: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    maxWidth: '800px',
    width: '90%',
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  pharmacyStoreHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    borderBottom: '2px solid #F7D9EB',
    paddingBottom: '1rem',
  },
  pharmacyInfoSection: {
    marginBottom: '2rem',
  },
  pharmacyDetailsSection: {
    display: 'flex',
    gap: '2rem',
    flexWrap: 'wrap',
  },
  pharmacyDistance: {
    color: '#666',
    fontSize: '0.9rem',
    margin: '0.5rem 0',
  },
  pharmacyDelivery: {
    color: '#4CAF50',
    fontSize: '0.9rem',
    margin: '0.5rem 0',
  },
  pharmacyRatingText: {
    color: '#FFD700',
    fontSize: '0.9rem',
    margin: '0.5rem 0',
  },
  pharmacyMedicines: {
    marginBottom: '2rem',
  },
  medicinesTitle: {
    color: '#7C2A62',
    marginBottom: '1rem',
    fontSize: '1.2rem',
  },
  medicinesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '1rem',
  },
  medicineItem: {
    border: '1px solid #F7D9EB',
    borderRadius: '8px',
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  medicineInfo: {
    marginBottom: '1rem',
  },
  medicineName: {
    margin: '0 0 0.5rem 0',
    color: '#7C2A62',
    fontSize: '1rem',
  },
  medicineCategory: {
    margin: '0 0 0.5rem 0',
    color: '#666',
    fontSize: '0.8rem',
  },
  medicinePrice: {
    margin: 0,
    color: '#7C2A62',
    fontWeight: 'bold',
    fontSize: '1.1rem',
  },
  addToCartPharmacyButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: '600',
  },
  noMedicinesFound: {
    gridColumn: '1 / -1',
    textAlign: 'center',
    padding: '2rem',
    color: '#666',
  },
  pharmacyActions: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1rem',
    marginTop: '1rem',
  },
  viewCartButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
  },
  backToPharmaciesButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '2px solid #7C2A62',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
  },

  // Appointment Details Modal
  appointmentDetailsModal: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    maxWidth: '700px',
    width: '90%',
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  appointmentDetailsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    borderBottom: '2px solid #F7D9EB',
    paddingBottom: '1rem',
  },
  appointmentDetailsContent: {
    marginBottom: '2rem',
  },
  detailSection: {
    marginBottom: '2rem',
  },
  detailSectionTitle: {
    color: '#7C2A62',
    marginBottom: '1rem',
    fontSize: '1.1rem',
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1rem',
  },
  detailItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  detailLabel: {
    color: '#666',
    fontSize: '0.9rem',
    fontWeight: '500',
  },
  detailValue: {
    color: '#333',
    fontSize: '1rem',
  },
  appointmentDetailsActions: {
    display: 'flex',
    justifyContent: 'center',
  },
  closeDetailsButton: {
    padding: '0.75rem 2rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'button',
    fontWeight: '600',
  },

  // Live Tracking
  liveTrackingContainer: {
    marginTop: '140px',
    padding: '2rem',
    minHeight: 'calc(100vh - 140px)',
    backgroundColor: '#f8fafc',
  },
  trackingHeader: {
    backgroundColor: 'white',
    padding: '1.5rem 2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    marginBottom: '2rem',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  backButton: {
    padding: '0.5rem 1rem',
    backgroundColor: 'transparent',
    color: '#7C2A62',
    border: '1px solid #7C2A62',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  trackingTitle: {
    margin: 0,
    color: '#7C2A62',
    fontSize: '1.8rem',
  },
  trackingSubtitle: {
    margin: 0,
    color: '#666',
    fontSize: '1rem',
  },
  trackingContent: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '2rem',
    height: '600px',
  },
  mapContainer: {
    backgroundColor: 'white',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    overflow: 'hidden',
    height: '100%',
  },
  trackingSidebar: {
    backgroundColor: 'white',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    padding: '1.5rem',
    overflowY: 'auto',
  },
  deliveryInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  sidebarTitle: {
    color: '#7C2A62',
    margin: '0 0 1rem 0',
    fontSize: '1.3rem',
  },
  progressSection: {
    marginBottom: '1rem',
  },
  progressBar: {
    height: '8px',
    backgroundColor: '#f0f0f0',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '0.5rem',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#7C2A62',
    transition: 'width 0.5s ease',
  },
  progressLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.8rem',
    color: '#666',
  },
  statusCard: {
    backgroundColor: '#f8f5ff',
    padding: '1rem',
    borderRadius: '10px',
    border: '1px solid #F7D9EB',
  },
  currentStatus: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.5rem',
  },
  statusLabel: {
    color: '#666',
    fontSize: '0.9rem',
  },
  statusValue: {
    color: '#7C2A62',
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  eta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  etaLabel: {
    color: '#666',
    fontSize: '0.9rem',
  },
  etaValue: {
    color: '#4CAF50',
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  deliveryPartner: {
    border: '1px solid #F7D9EB',
    borderRadius: '10px',
    padding: '1rem',
  },
  partnerTitle: {
    color: '#7C2A62',
    margin: '0 0 1rem 0',
    fontSize: '1.1rem',
  },
  partnerInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '1rem',
  },
  partnerAvatar: {
    width: '50px',
    height: '50px',
    borderRadius: '50%',
    backgroundColor: '#F7D9EB',
    color: '#7C2A62',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    fontSize: '1.2rem',
  },
  partnerDetails: {
    flex: 1,
  },
  partnerName: {
    margin: '0 0 0.25rem 0',
    fontWeight: '600',
    color: '#333',
  },
  partnerVehicle: {
    margin: '0 0 0.25rem 0',
    color: '#666',
    fontSize: '0.9rem',
  },
  partnerRating: {
    color: '#FFD700',
    fontWeight: 'bold',
    fontSize: '0.9rem',
  },
  callButton: {
    width: '100%',
    padding: '0.75rem',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
  },
  orderSummary: {
    border: '1px solid #F7D9EB',
    borderRadius: '10px',
    padding: '1rem',
  },
  summaryTitleText: {
    color: '#7C2A62',
    margin: '0 0 1rem 0',
    fontSize: '1.1rem',
  },
  orderSummaryItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.5rem 0',
    borderBottom: '1px solid #f0f0f0',
  },

  // Chatbot Styles
  chatbotIconContainer: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.5rem',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    border: '1px solid rgba(255, 255, 255, 0.2)',
  },
  chatbotIcon: {
    fontSize: '1.5rem',
  },
  chatbotContainer: {
    position: 'fixed',
    bottom: '20px',
    right: '20px',
    width: '350px',
    height: '500px',
    backgroundColor: 'white',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    zIndex: 2000,
    display: 'flex',
    flexDirection: 'column',
    border: '1px solid #e0e0e0',
  },
  chatbotHeader: {
    padding: '1rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    borderTopLeftRadius: '15px',
    borderTopRightRadius: '15px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexShrink: 0,
  },
  chatbotTitle: {
    margin: 0,
    fontSize: '1.1rem',
    fontWeight: '600',
  },
  closeChatbot: {
    background: 'none',
    border: 'none',
    color: 'white',
    fontSize: '1.5rem',
    cursor: 'pointer',
    padding: '0',
    width: '30px',
    height: '30px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    transition: 'background-color 0.2s ease',
  },
  chatMessages: {
    flex: 1,
    padding: '1rem',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    backgroundColor: '#fafafa',
  },
  chatMessage: {
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '85%',
  },
  userMessage: {
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
  },
  botMessage: {
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
  },
  messageBubble: {
    padding: '0.75rem 1rem',
    borderRadius: '15px',
    fontSize: '0.9rem',
    lineHeight: '1.4',
    wordWrap: 'break-word',
    maxWidth: '100%',
  },
  userMessageBubble: {
    backgroundColor: '#7C2A62',
    color: 'white',
    borderBottomRightRadius: '5px',
  },
  botMessageBubble: {
    backgroundColor: '#e0e0e0',
    color: '#333',
    borderBottomLeftRadius: '5px',
  },
  messageTime: {
    fontSize: '0.7rem',
    color: '#666',
    marginTop: '0.25rem',
    padding: '0 0.5rem',
  },
  chatInputContainer: {
    padding: '1rem',
    borderTop: '1px solid #e0e0e0',
    display: 'flex',
    gap: '0.5rem',
    backgroundColor: 'white',
    borderBottomLeftRadius: '15px',
    borderBottomRightRadius: '15px',
    flexShrink: 0,
  },
  chatInput: {
    flex: 1,
    padding: '0.75rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '25px',
    fontSize: '0.9rem',
    outline: 'none',
    transition: 'border-color 0.2s ease',
    backgroundColor: '#f8f9fa',
  },
  sendButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    fontWeight: '600',
    fontSize: '0.9rem',
    transition: 'all 0.2s ease',
    minWidth: '60px',
  },

  // Doctor Chat Modal
  doctorChatModal: {
    backgroundColor: 'white',
    padding: '0',
    borderRadius: '15px',
    boxShadow: '0 10px 30px rgba(0,0,0,0.3)',
    width: '450px',
    height: '650px',
    display: 'flex',
    flexDirection: 'column',
  },
  doctorChatHeader: {
    padding: '1rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    borderTopLeftRadius: '15px',
    borderTopRightRadius: '15px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  doctorChatInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    flex: 1,
  },
  doctorChatActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  goBackButton: {
    padding: '0.5rem 1rem',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    color: 'white',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: '500',
    transition: 'all 0.2s ease',
  },
  doctorImageSmall: {
    fontSize: '2rem',
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: '50%',
  },
  doctorChatName: {
    margin: 0,
    fontSize: '1.1rem',
    fontWeight: '600',
  },
  doctorChatSpecialty: {
    margin: 0,
    fontSize: '0.9rem',
    opacity: 0.9,
  },
  doctorChatMessages: {
    flex: 1,
    padding: '1rem',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    backgroundColor: '#fafafa',
  },
  doctorChatInputContainer: {
    padding: '1rem',
    borderTop: '1px solid #e0e0e0',
    display: 'flex',
    gap: '0.5rem',
    backgroundColor: 'white',
    borderBottomLeftRadius: '15px',
    borderBottomRightRadius: '15px',
  },
  doctorChatInput: {
    flex: 1,
    padding: '0.75rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '25px',
    fontSize: '0.9rem',
    outline: 'none',
  },
  closeModalButton: {
    background: 'none',
    border: 'none',
    fontSize: '1.8rem',
    cursor: 'pointer',
    color: 'white',
    padding: '0',
    width: '35px',
    height: '35px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    transition: 'background-color 0.2s ease',
  },

  // Page Header with Back Button
  pageHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '2rem',
  },

  // NEW STYLES - Emergency Mode Styles
  emergencyModeSection: {
    marginTop: '1.5rem',
    padding: '1rem',
    backgroundColor: '#FFF3CD',
    border: '2px solid #FFC107',
    borderRadius: '10px',
    textAlign: 'center',
  },
  emergencyModeToggle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1rem',
    cursor: 'pointer',
  },
  emergencyModeSlider: {
    width: '50px',
    height: '25px',
    backgroundColor: '#ccc',
    borderRadius: '25px',
    position: 'relative',
    transition: 'background-color 0.3s ease',
  },
  emergencyModeText: {
    fontWeight: 'bold',
    color: '#666',
  },
  emergencyModeNote: {
    marginTop: '0.5rem',
    fontSize: '0.9rem',
    color: '#D32F2F',
    fontWeight: '500',
  },

  // NEW STYLES - Wallet Balance Preview
  walletBalancePreview: {
    margin: '1rem 0',
    padding: '0.75rem',
    backgroundColor: '#F8F9FA',
    borderRadius: '8px',
    textAlign: 'center',
    fontWeight: '600',
    color: '#7C2A62',
  },

  // NEW STYLES - Offers Section
  offersSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
    marginTop: '2rem',
  },
  offersGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  },
  offerCard: {
    padding: '1.5rem',
    border: '2px solid #FFD700',
    borderRadius: '10px',
    backgroundColor: '#FFFDE7',
    position: 'relative',
  },
  offerBadge: {
    position: 'absolute',
    top: '-10px',
    right: '-10px',
    backgroundColor: '#FF6B6B',
    color: 'white',
    borderRadius: '50%',
    width: '30px',
    height: '30px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.8rem',
  },
  offerCode: {
    color: '#7C2A62',
    fontWeight: 'bold',
    marginBottom: '0.5rem',
  },
  offerDescription: {
    color: '#666',
    fontSize: '0.9rem',
    marginBottom: '0.5rem',
  },
  offerValidity: {
    color: '#999',
    fontSize: '0.8rem',
  },

  // NEW STYLES - Family Profiles Styles
  familyProfilesSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  familyHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
  },
  addFamilyButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
  },
  familyForm: {
    backgroundColor: '#F8F9FA',
    padding: '2rem',
    borderRadius: '10px',
    marginBottom: '2rem',
    border: '1px solid #E9ECEF',
  },
  familyMembersGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '1.5rem',
  },
  familyMemberCard: {
    border: '2px solid #F7D9EB',
    borderRadius: '10px',
    padding: '1.5rem',
    backgroundColor: 'white',
  },
  memberHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '1rem',
  },
  memberName: {
    color: '#7C2A62',
    margin: '0',
    fontSize: '1.1rem',
  },
  memberActions: {
    display: 'flex',
    gap: '0.5rem',
  },
  editButton: {
    padding: '0.25rem 0.75rem',
    backgroundColor: '#FF9800',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.8rem',
  },
  memberDetails: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },

  // NEW STYLES - Health Records Styles
  healthRecordsSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  recordsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
  },
  uploadRecordButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
  },
  uploadForm: {
    backgroundColor: '#F8F9FA',
    padding: '2rem',
    borderRadius: '10px',
    marginBottom: '2rem',
    border: '1px solid #E9ECEF',
  },
  fileInput: {
    width: '100%',
    padding: '0.75rem',
    border: '2px solid #F7D9EB',
    borderRadius: '8px',
    backgroundColor: 'white',
  },
  fileInfo: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '0.5rem',
    fontSize: '0.9rem',
    color: '#666',
  },
  recordsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))',
    gap: '1.5rem',
  },
  recordCard: {
    border: '2px solid #F7D9EB',
    borderRadius: '10px',
    padding: '1.5rem',
    backgroundColor: 'white',
  },
  recordHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1rem',
    marginBottom: '1rem',
  },
  recordIcon: {
    fontSize: '2rem',
    width: '50px',
    height: '50px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7D9EB',
    borderRadius: '10px',
  },
  recordInfo: {
    flex: 1,
  },
  recordName: {
    color: '#7C2A62',
    margin: '0 0 0.5rem 0',
    fontSize: '1.1rem',
  },
  recordMeta: {
    display: 'flex',
    gap: '1rem',
    fontSize: '0.9rem',
    color: '#666',
  },
  recordType: {
    backgroundColor: '#E3F2FD',
    color: '#1976D2',
    padding: '0.25rem 0.5rem',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  recordDate: {
    color: '#666',
  },
  deleteRecordButton: {
    background: 'none',
    border: 'none',
    fontSize: '1.2rem',
    cursor: 'pointer',
    color: '#FF6B6B',
  },
  recordDetails: {
    borderTop: '1px solid #F7D9EB',
    paddingTop: '1rem',
  },
  recordDescription: {
    color: '#666',
    margin: '0 0 1rem 0',
    fontSize: '0.9rem',
  },
  fileActions: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1rem',
  },
  viewFileButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#2196F3',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.8rem',
  },
  downloadButton: {
    padding: '0.5rem 1rem',
    backgroundColor: '#4CAF50',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    textDecoration: 'none',
    display: 'inline-block',
  },

  // NEW STYLES - Wallet Styles
  walletSection: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '15px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  walletBalanceCard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '2rem',
    backgroundColor: '#7C2A62',
    color: 'white',
    borderRadius: '15px',
    marginBottom: '2rem',
  },
  balanceInfo: {
    flex: 1,
  },
  balanceLabel: {
    margin: '0 0 0.5rem 0',
    fontSize: '1.1rem',
    opacity: 0.9,
  },
  balanceAmount: {
    margin: '0 0 0.5rem 0',
    fontSize: '2.5rem',
    fontWeight: 'bold',
  },
  balanceSubtext: {
    margin: 0,
    opacity: 0.8,
    fontSize: '0.9rem',
  },
  walletActions: {
    display: 'flex',
    gap: '1rem',
  },
  topUpButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'white',
    color: '#7C2A62',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '1rem',
  },
  topUpSection: {
    backgroundColor: '#F8F9FA',
    padding: '2rem',
    borderRadius: '10px',
    marginBottom: '2rem',
    border: '1px solid #E9ECEF',
  },
  presetAmounts: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1.5rem',
    flexWrap: 'wrap',
  },
  presetAmountButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'white',
    color: '#7C2A62',
    border: '2px solid #F7D9EB',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: '600',
    transition: 'all 0.3s ease',
  },
  presetAmountButtonActive: {
    backgroundColor: '#7C2A62',
    color: 'white',
    borderColor: '#7C2A62',
  },
  topUpForm: {
    marginTop: '1.5rem',
  },
  amountInputContainer: {
    display: 'flex',
    alignItems: 'center',
    border: '2px solid #F7D9EB',
    borderRadius: '8px',
    overflow: 'hidden',
    backgroundColor: 'white',
  },
  currencySymbol: {
    padding: '0.75rem',
    backgroundColor: '#F7D9EB',
    color: '#7C2A62',
    fontWeight: 'bold',
  },
  amountInput: {
    flex: 1,
    padding: '0.75rem',
    border: 'none',
    outline: 'none',
    fontSize: '1rem',
    backgroundColor: 'transparent',
  },
  amountNote: {
    color: '#666',
    fontSize: '0.8rem',
    marginTop: '0.25rem',
  },
  paymentMethods: {
    display: 'flex',
    gap: '1rem',
    marginTop: '0.5rem',
  },
  paymentMethod: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
  },
  paymentMethodLabel: {
    fontSize: '0.9rem',
  },
  transactionSection: {
    marginTop: '2rem',
  },
  transactionList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  transactionItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem',
    border: '1px solid #F7D9EB',
    borderRadius: '8px',
    backgroundColor: 'white',
  },
  transactionIcon: {
    fontSize: '1.5rem',
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7D9EB',
    borderRadius: '50%',
  },
  transactionInfo: {
    flex: 1,
  },
  transactionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.25rem',
  },
  transactionDescription: {
    fontWeight: '600',
    color: '#333',
  },
  transactionAmount: {
    fontWeight: 'bold',
    fontSize: '1.1rem',
  },
  transactionFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  transactionDate: {
    color: '#666',
    fontSize: '0.8rem',
  },
  transactionStatus: {
    fontSize: '0.8rem',
    fontWeight: '500',
  },
  walletBenefits: {
    marginTop: '2rem',
    paddingTop: '2rem',
    borderTop: '2px solid #F7D9EB',
  },
  benefitsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '1.5rem',
    marginTop: '1rem',
  },
  benefitItem: {
    textAlign: 'center',
    padding: '1.5rem',
    border: '1px solid #F7D9EB',
    borderRadius: '10px',
    backgroundColor: '#FAFAFA',
  },
  benefitIcon: {
    fontSize: '2rem',
    marginBottom: '1rem',
  },
  benefitTitle: {
    color: '#7C2A62',
    margin: '0 0 0.5rem 0',
    fontSize: '1rem',
  },
  benefitText: {
    color: '#666',
    fontSize: '0.9rem',
    margin: 0,
    lineHeight: '1.4',
  },

  // NEW STYLES - Empty State Styles
  emptyState: {
    textAlign: 'center',
    padding: '3rem 1rem',
    color: '#666',
  },
  emptyStateIcon: {
    fontSize: '4rem',
    marginBottom: '1rem',
  },
  emptyStateText: {
    margin: '0 0 0.5rem 0',
    fontSize: '1.3rem',
    fontWeight: '600',
  },
  emptyStateSubtext: {
    margin: '0 0 2rem 0',
    fontSize: '1rem',
    color: '#999',
  },

  // NEW STYLES - Detail Item Styles
  detailItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '0.5rem 0',
    borderBottom: '1px solid #f0f0f0',
  },
  detailLabel: {
    color: '#666',
    fontSize: '0.9rem',
    fontWeight: '500',
  },
  detailValue: {
    color: '#333',
    fontSize: '0.9rem',
    fontWeight: '600',
  },
};

/* 🔥 RESPONSIVE MEDIA QUERIES */
export const responsiveStyles = {
  '@media (max-width: 480px)': {
    headerTop: {
      padding: '0.5rem 0.8rem',
      flexDirection: 'row',
    },
    userSection: {
      flexDirection: 'row',
    },
    headerBottom: {
      padding: '0.4rem 0.5rem',
    },
    navButton: {
      padding: '0.4rem 0.6rem',
      fontSize: '0.7rem',
    },
    logo: {
      fontSize: '1.2rem',
    },
    userWelcome: {
      display: 'none',
    },
    logoutButton: {
      padding: '0.4rem 0.8rem',
      fontSize: '0.75rem',
    },
    cartIcon: {
      fontSize: '1.2rem',
    },
    notificationBell: {
      fontSize: '1.2rem',
    },
    chatbotIcon: {
      fontSize: '1.2rem',
    },
    mainContent: {
      marginTop: '95px',
    },
    // Add responsive styles for other components
    medicineLayout: {
      marginTop: '95px',
      padding: '1rem',
    },
    profileContainer: {
      marginTop: '95px',
      padding: '1rem',
    },
    consultationContainer: {
      marginTop: '95px',
      padding: '1rem',
    },
    cartPageContainer: {
      marginTop: '95px',
      padding: '1rem',
    },
  },
  '@media (max-width: 768px)': {
    mainContent: {
      marginTop: '100px',
    },
    // Add tablet responsive styles
  },
};